apiVersion: apps/v1
kind: Deployment
metadata:
  name: zyoud-vault
  namespace: zyoud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zyoud-vault
  template:
    metadata:
      labels:
        app: zyoud-vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:1.15
          args:
            - "server"
            - "-dev"
            - "-dev-listen-address=0.0.0.0:8205"
          ports:
            - containerPort: 8205
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: zyoud-root-token
            - name: VAULT_ADDR
              value: http://127.0.0.1:8205
---
apiVersion: v1
kind: Service
metadata:
  name: zyoud-vault
  namespace: zyoud
spec:
  selector:
    app: zyoud-vault
  ports:
    - name: http
      port: 8205
      targetPort: 8205
