apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zyoud-postgres
  namespace: zyoud
spec:
  serviceName: zyoud-postgres
  replicas: 1
  selector:
    matchLabels:
      app: zyoud-postgres
  template:
    metadata:
      labels:
        app: zyoud-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          args: ["-p", "5544"]
          ports:
            - containerPort: 5544
          envFrom:
            - secretRef:
                name: zyoud-app-secrets
          volumeMounts:
            - name: zyoud-db-data
              mountPath: /var/lib/postgresql/data
            - name: zyoud-init
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: zyoud-init
          configMap:
            name: zyoud-postgres-init
  volumeClaimTemplates:
    - metadata:
        name: zyoud-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zyoud-postgres
  namespace: zyoud
spec:
  selector:
    app: zyoud-postgres
  ports:
    - name: pg
      port: 5544
      targetPort: 5544
