apiVersion: apps/v1
kind: Deployment
metadata:
  name: zyoud-backend
  namespace: zyoud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zyoud-backend
  template:
    metadata:
      labels:
        app: zyoud-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/zyouud/apptraining/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4100
          envFrom:
            - secretRef:
                name: zyoud-app-secrets
          env:
            - name: DB_HOST
              value: zyoud-postgres
            - name: DB_PORT
              value: "5544"
            - name: PORT
              value: "4100"
---
apiVersion: v1
kind: Service
metadata:
  name: zyoud-backend
  namespace: zyoud
spec:
  selector:
    app: zyoud-backend
  ports:
    - name: http
      port: 4100
      targetPort: 4100
