apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zyoud-app-ingress
  namespace: zyoud
  annotations:
    cert-manager.io/cluster-issuer: zyoud-letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - devops-3.sociumtech.com
      secretName: zyoud-devops-3-tls
  rules:
    - host: devops-3.sociumtech.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: zyoud-backend
                port:
                  number: 4100
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zyoud-frontend
                port:
                  number: 4200
