apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zyoud-letsencrypt
spec:
  acme:
    email: zyoud@sociumtech.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: zyoud-letsencrypt-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zyoud-devops-3-tls
  namespace: zyoud
spec:
  secretName: zyoud-devops-3-tls
  dnsNames:
    - devops-3.sociumtech.com
  issuerRef:
    name: zyoud-letsencrypt
    kind: ClusterIssuer
