apiVersion: v1
kind: ServiceAccount
metadata:
  name: zyoud-vault-fetch-sa
  namespace: zyoud
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zyoud-vault-fetch-role
  namespace: zyoud
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","list","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zyoud-vault-fetch-rb
  namespace: zyoud
subjects:
  - kind: ServiceAccount
    name: zyoud-vault-fetch-sa
    namespace: zyoud
roleRef:
  kind: Role
  name: zyoud-vault-fetch-role
  apiGroup: rbac.authorization.k8s.io
